### ISSUE TITLE
Compiling instructions

### ISSUE THREAD

**Issue by junocomp** [fredldotme/opticd#1]
I would like to try this on Droidian, is it possible you can tell me how to compile it?

**Comment by junocomp** [comment]
Actually, please disregard that. I managed to compile.

After running I get

$ opticd 
could not connect to server

EGL not initialized
Aborted (core dumped)

**Comment by fredldotme** [comment]
That might be because the opticd EGL helper is connecting to Mirclient, and not Wayland right now.
What needs to happen is that Wayland is prefered and it only falls back to Mir later on.

**Comment by junocomp** [comment]
@fredldotme makes sense. Does opticd supports Wayland, if so. Is there something that I can change manually or does it need to be further developed?

**Comment by fredldotme** [comment]
Nothing requires Mirclient specifically, the same code can be used, it just needs the EGL connection done over Wayland, that should be 3 lines of code to change.

**Comment by fredldotme** [comment]
It needs these two Mirclient calls replaced with typical Wayland connection handling: https://github.com/fredldotme/opticd/blob/main/src/eglhelper.cpp#L14

**Comment by junocomp** [comment]
I replaced mir_socket with wayland-0 and recompiled.

No errors when executing opticd. 

I have also compiled the kernel with v4l2loopback.

When running opticd and opening a webcam app, for example cheese it still doesn't detect it.

**Comment by fredldotme** [comment]
Closed as fixed, see: https://github.com/fredldotme/opticd/commit/d8872cd46e6682a4c60fe670c0f81f60501f0d65
